---
- hosts: all
  tasks:


  - name: Install python3
    yum: "name={{ item }} state=installed"
    become: yes
    with_items:
        - centos-release-scl
        - yum-utils
        - git
        - curl
        - wget

  - name: Repo      
    shell: yum install -y https://centos7.iuscommunity.org/ius-release.rpm
    become: yes
        #- python36u
        #- python36u-pip
        #- python36u-devel

  - name: copy file  
    shell: sudo yum install -y python36u python36u-libs python36u-devel python36u-pip
    become: yes
    become_user: centos

  - name: awscli
    shell: pip3.6 install awscli --upgrade --user
    become: yes
    become_user: centos

  - name: boto3
    shell: pip3.6 install boto3 botocore --upgrade --user
    become: yes
    become_user: centos 

 # - name: Copy file with module
 #   aws_s3: 
 #     bucket: vpc-states
 #     object: ibm-cloud-private-x86_64-3.1.2.tar.gz
 #     dest: /tmp/ibm-cloud-private-x86_64-3.1.2.tar.gz
 #     mode: get 


 # - name: Copy
 #   shell: aws s3 cp  s3://vpc-states/ibm-cloud-private-x86_64-3.1.2.tar.gz /tmp/

