---
- hosts: 127.0.0.1
  roles: 
    #- geerlingguy.docker
    #- ansible-role-users-master 
  
  tasks:

  - name: Install python3
    yum: "name={{ item }} state=installed"
    become: yes
    with_items:
        - centos-release-scl
        - yum-utils
        - git
        - curl
        - wget
        - vim 
        - maven 

  - name: copy file  
    shell: sudo yum install -y python36u python36u-libs python36u-devel python36u-pip
    become: yes

  - name: awscli
    shell: pip3.6 install awscli --upgrade --user
    become: yes

  - name: boto3
    shell: pip3.6 install boto3 botocore --upgrade --user
    become: yes

  
