---
- hosts: all
  become: true
  remote_user: centos 

  tasks: 
    - name: Install nginx
      yum: 
        name: nginx 
        state: installed 

  roles:
    #- ansible-role-jenkins
    - ansible-role-redmine

