---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Install sshd package
      apt:
        name: openssh-server
        state: present
    - name: Add user john
      user:
        name: john
        state: present
